'use strict'

var en = {"gainMuscle":"GAIN MUSCLE",
		  "loseFat":"LOSE FAT",
		  "onlineCoaching":"ONLINE COACHING",
		  "ebooks":"E-BOOKS",
		  "about":"ABOUT",
		  "whatDoYouWantToDo":"What do you want to do?",
		  "loseWeight":"LOSE WEIGHT",
		  "maintainWeight":"MAINTAIN WEIGHT",
		  "gainWeight":"GAIN WEIGHT",
		  "selectGender":"SELECT GENDER",
		  "male":"MALE",
		  "female":"FEMALE",
		  "typeOfProgress":"TYPE OF PROGRESS",
		  "slow":"REGULAR - SLOW",
		  "fast":"FAST - DRAMATIC",
		  "justOneMoreStep":"JUST ONE MORE STEP",
		  "name":"NAME",
		  "lastName":"LAST NAME",
		  "email":"EMAIL",
		  "weight":"WEIGHT KG",
		  "height":"HEIGHT CM",
		  "contactFormBtn":"VIEW RESULTS",
		  "gramsPerDay":"GRAMS PER DAY",
		  "carbohidrates":"CARBOHYDRATES",
		  "proteins":"PROTEINS",
		  "fatsselect":"FATS",
		  "siteLinks":"SITE LINKS",
		  "fatLossProgram":"FAT LOSS PROGRAM",
		  "gainMuscleProgram":"GAIN MUSCLE PROGRAM",
		  "home":"HOME",
		  "contact":"CONTACT",
		  "ebook":"E-BOOK",
		  "foodGuide":"FOOD GUIDE",
		  "trainingGuide":"TRAINING GUIDE",
		  "primeCombo":"PRIME COMBO",
		  "select":"SELECT",
		  "selected":"Languaje",
		  "allRightReserved":"All right reserved"};
		  
var es = {"gainMuscle":"GAIN MUSCLE",
		  "loseFat":"LOSE FAT",
		  "onlineCoaching":"ONLINE COACHING",
		  "ebooks":"E-BOOKS",
		  "about":"NOSOTROS",
		  "whatDoYouWantToDo":"¿Que quieres hacer?",
		  "loseWeight":"PERDER PESO",
		  "maintainWeight":"MANTENER PESO",
		  "gainWeight":"GANAR PESO",
		  "selectGender":"SELECCIONAR GENERO",
		  "male":"HOMBRE",
		  "female":"MUJER",
		  "typeOfProgress":"PROGRESO",
		  "slow":"REGULAR - LENTO",
		  "fast":"RAPIDO - DRAMATICO",
		  "justOneMoreStep":"SOLO UN PASO MÁS",
		  "name":"NOMBRE",
		  "lastName":"APELLIDO",
		  "email":"EMAIL",
		  "weight":"PESO KG",
		  "height":"ALTURA CM",
		  "contactFormBtn":"VER RESULTADOS",
		  "gramsPerDay":"GRAMOS POR DÍA",
		  "carbohidrates":"CARBOHIDRATOS",
		  "proteins":"PROTEINAS",
		  "fatsselect":"GRASAS",
		  "siteLinks":"VINCULOS",
		  "fatLossProgram":"PERDIDA DE GRASA",
		  "gainMuscleProgram":"GANAR MÚSCULO",
		  "home":"INICIO",
		  "contact":"CONTACTO",
		  "ebook":"E-BOOK",
		  "foodGuide":"GUÍA",
		  "trainingGuide":"GUÍA DE ENTRENAMIENTO",
		  "primeCombo":"PRIME COMBO",
		  "select":"SELECCIONAR",
		  "selected":"Idioma",
		  "allRightReserved":"Todos los drechos reservados"};

var de = {"gainMuscle":"MUSKELAUFBAU",
		  "loseFat":"ABNEHMEN",
		  "onlineCoaching":"ONLINE COACHING",
		  "ebooks":"E-BÜCHER",
		  "about":"UNS",
		  "whatDoYouWantToDo":"Was willst du machen",
		  "loseWeight":"GEWICHT VERLIEREN",
		  "maintainWeight":"GEWICHT BEHALTEN",
		  "gainWeight":"GEWICHT GEWINNEN",
		  "selectGender":"GENDER WÄHLEN",
		  "male":"MANN",
		  "female":"FRAU",
		  "typeOfProgress":"FORTSCHRITT",
		  "slow":"REGELMÄSSIG - LANGSAM",
		  "fast":"SCHNELL - DRAMATISCH",
		  "justOneMoreStep":"NUR EIN SCHRITT MEHR",
		  "name":"NAME",
		  "lastName":"NACHNAME",
		  "email":"E-MAIL",
		  "weight":"GEWICHT KG",
		  "height":"HÖHE CM",
		  "contactFormBtn":"ERGEBNISSE SEHEN",
		  "gramsPerDay":"GRAMM PRO TAG",
		  "carbohidrates":"Kohlenhydrate",
		  "proteins":"PROTEINE",
		  "fatsselect":"FETTE",
		  "siteLinks":"LINKS",
		  "fatLossProgram":"FETTVERLUST",
		  "gainMuscleProgram":"GEWINNEN SIE MUSKEL",
		  "home":"START",
		  "contact":"KONTAKT",
		  "ebook":"E-BÜCHER",
		  "foodGuide":"GUIDE",
		  "trainingGuide":"TRAININGSANLEITUNG",
		  "primeCombo":"PRIME COMBO",
		  "select":"SELECT",
		  "selected":"Languaje",
		  "allRightReserved":"Alle rechte vorbehalten"};